const path = {
  home: '/',
  login: '/login',
  register: '/register',
  profile: '/profile',
  changePassword: '/change-password',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  logout: '/logout',
  healthAZ: '/health-a-z',
  disease: '/health-a-z/:id',
  medicines: '/drugs-and-supplements',
  medicine: '/drugs-and-supplements/:id',
  reading: '/readings',
  order: '/orders/:id',
  checkout: '/checkout',
  paymentSuccess: '/payment-success',
  doctors: '/doctors',
  doctor: '/doctors/:id',
  doctorSymptomSearch: '/doctors/search/symptoms',
  appointments: '/appointments',
  appointment: '/appointments/:id',
  appointmentBooking: '/appointments/book/:doctorId',
  feedback: '/feedback',
  comicDetail: '/truyen-tranh/:slug',
  chapter: '/truyen-tranh/:slug/chapter/:chapterNumber',
  follow: '/follow',
};

export default path;
